export const SUPPORTED_LANGUAGES = [
    'Ada',
    'Bash',
    'C#',
    'C++',
    'COBOL',
    'CSS',
    'Clojure',
    'Dart',
    'Dockerfile',
    'Elixir',
    'Erlang',
    'F#',
    'Fortran',
    'Go',
    'GraphQL',
    'Groovy',
    'Haskell',
    'HTML',
    'Java',
    'JavaScript',
    'JSON',
    'Kotlin',
    'Less',
    'Lisp',
    'Lua',
    'Makefile',
    'MATLAB',
    'Markdown',
    'OCaml',
    'Objective-C',
    'Pascal',
    'Perl',
    'PHP',
    'PowerShell',
    'Prolog',
    'Python',
    'R',
    'Ruby',
    'Rust',
    'SASS',
    'Scheme',
    'Scala',
    'Solidity',
    'SQL',
    'Swift',
    'TypeScript',
    'TOML',
    'WebAssembly',
    'XML',
    'YAML',
]

// Map a language display name to a common file extension (lowercase, without dot).
// Values are best-effort and used only for validation / suggested filenames.
export function getExtensionForLanguage(lang: string): string {
    const m: Record<string, string> = {
        'ada': 'adb',
        'bash': 'sh',
        'c': 'c',
        'c#': 'cs',
        'c++': 'cpp',
        'clojure': 'clj',
        'cobol': 'cob',
        'css': 'css',
        'dart': 'dart',
        'dockerfile': '',
        'elixir': 'ex',
        'erlang': 'erl',
        'f#': 'fs',
        'fortran': 'f90',
        'go': 'go',
        'graphql': 'graphql',
        'groovy': 'groovy',
        'haskell': 'hs',
        'html': 'html',
        'java': 'java',
        'javascript': 'js',
        'json': 'json',
        'kotlin': 'kt',
        'less': 'less',
        'lisp': 'lisp',
        'lua': 'lua',
        'makefile': '',
        'matlab': 'm',
        'markdown': 'md',
        'ocaml': 'ml',
        'objective-c': 'm',
        'pascal': 'pas',
        'perl': 'pl',
        'php': 'php',
        'powershell': 'ps1',
        'prolog': 'pl',
        'python': 'py',
        'r': 'r',
        'ruby': 'rb',
        'rust': 'rs',
        'sass': 'sass',
        'scss': 'scss',
        'scheme': 'scm',
        'scala': 'scala',
        'solidity': 'sol',
        'sql': 'sql',
        'swift': 'swift',
        'toml': 'toml',
        'typescript': 'ts',
        'webassembly': 'wasm',
        'xml': 'xml',
        'yaml': 'yaml',
    }

    return m[(lang || '').toLowerCase()] ?? 'txt'
}
